### ISSUE TITLE
`0 asset files hashed`

### ISSUE THREAD

**Issue by S1SYPHOS** [johannschopplich/hashup#1]
**// Update:** Merge me :pray: 

Help me :fox_face: 

```text
🚀 ls public/assets/styles
main.css

🚀 ./node_modules/hashup/bin/hashup.cjs public/assets/styles
hashup v0.3.2
start hashing build assets...
ℹ included file extensions: css, js
✔ 0 asset files hashed in public/assets/styles
```

**Comment by S1SYPHOS** [comment]
As it turns out, there's a duplicate `{${extensions.join(",")}}` inside your `glob` call - see #2.

**Comment by johannschopplich** [comment]
Actually, it's a feature, not a bug. 😄 hashup expects the directories `assets/css` as well as `assets/js`, which are defaults from Kirby. Resulting in `assets/css/**/*.css` and `assets/js/**/*.js` respectively. You may take a look into the source code for [`realtroll.de`](https://github.com/johannschopplich/realtroll.de) for an example.

For custom asset paths, we would have to introduce a new option.

**Comment by S1SYPHOS** [comment]
Noooo way I didn't see this - my bad! I'll adjust my `assets` path right away :woman_dancing:

**Comment by johannschopplich** [comment]
Thanks for taking the time for the PR tho. Much appreciated. 🙂

**Comment by S1SYPHOS** [comment]
For you, anything!
